services:
  sugarcube-server:
    build:
      context: ../SugarCube-server-main/SugarCube-server-main
      
      dockerfile: Dockerfile

    container_name: sugarcube-server
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
    restart: always

  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data: